# Generated by Django 4.2.30 on 2026-05-27 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_index', models.IntegerField(help_text='Row index in the original file')),
                ('source_row_raw', models.JSONField(help_text='Exact raw dict before normalisation')),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(help_text='e.g. stationary_combustion, electricity, air_travel', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('quantity_raw', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_raw', models.CharField(max_length=50)),
                ('quantity_normalised', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_normalised', models.CharField(help_text='Always kWh or tCO2e', max_length=50)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text='e.g. DEFRA 2023, IPCC AR6', max_length=100)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='plant_code, meter_id, route, etc.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=255)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True after approval + audit sign-off')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.rawingestion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='emissions_e_tenant__5a7e62_idx'), models.Index(fields=['tenant', 'scope'], name='emissions_e_tenant__80b9f6_idx'), models.Index(fields=['tenant', 'activity_date'], name='emissions_e_tenant__a4863c_idx')],
            },
        ),
    ]
