# Generated by Django 4.2.30 on 2026-05-27 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('raw_file', models.FileField(upload_to='raw_ingestions/')),
                ('row_count', models.IntegerField(default=0)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestions', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Raw Ingestions',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
